In [10]:
#used for data analysis and associated manipulation of tabular data
import pandas as pd  
lst = [
         ['smita', '20BCS4643', 'IOT', 'Maharashtra', '90'], 
         ['sakshi', '20BPT1234', 'IT', 'Maharashtra', '70'], 
         ['sushant', '20BCS3708', 'IS', 'Punjab', '60'],
         ['radhika', '20BCS3710', 'IS', 'Himachal', '80'], 
         ['ankur', '20BCS5643', 'BD', 'Madya-pradesh', '90'], 
         ['jasmeet', '20BCS5633', 'AIML', 'Uttar- pradesh', '70'], 
         ['rakshita', '20BCS1223', 'BD', 'kerala', '90'], 
         ['rachana', '20BCS4233', 'CSE', 'Maharashtra', '90'], 
         ['kartikey', '20BCS3627', 'IS', 'Himachal', '50'], 
         ['Akanksha', '20BCS2143', 'CC', 'Goa', '90'], 
]
       

df = pd.DataFrame(lst, columns =['Name' , 'UID' , 'Program Name' , 'State' ,'% marks']) 

print(df )

       Name        UID Program Name           State % marks
0     smita  20BCS4643          IOT     Maharashtra      90
1    sakshi  20BPT1234           IT     Maharashtra      70
2   sushant  20BCS3708           IS          Punjab      60
3   radhika  20BCS3710           IS        Himachal      80
4     ankur  20BCS5643           BD   Madya-pradesh      90
5   jasmeet  20BCS5633         AIML  Uttar- pradesh      70
6  rakshita  20BCS1223           BD          kerala      90
7   rachana  20BCS4233          CSE     Maharashtra      90
8  kartikey  20BCS3627           IS        Himachal      50
9  Akanksha  20BCS2143           CC             Goa      90

In [11]:
df.to_csv('file1.csv')

In [9]:
df

       Name        UID Program Name           State % marks
0   joydeep  20BCS4604          IOT          Bengal      90
1    sakshi  20BPT1234           IT     Maharashtra      70
2   sushant  20BCS3708           IS          Punjab      60
3   radhika  20BCS3710           IS        Himachal      80
4     ankur  20BCS5643           BD   Madya-pradesh      90
5   jasmeet  20BCS5633         AIML  Uttar- pradesh      70
6  rakshita  20BCS1223           BD          kerala      90
7   rachana  20BCS4233          CSE     Maharashtra      90
8  kartikey  20BCS3627           IS        Himachal      50
9  Akanksha  20BCS2143           CC             Goa      90