In [7]:
import pickle

def createFile():
    file = open("book.dat","ab")
    BookNo = int(input("Enter book number: "))
    Book_Name = input("Enter book Name: ")
    Author =input("Enter author: ")
    Price = int(input("Enter price: "))
    record = [BookNo, Book_Name, Author, Price]
    pickle.dump(record, file)
    file.close()
    
def countRec(Author):
    file = open("book.dat","rb")
    count = 0
    try:
        while True:
            record = pickle.load(file)
            if record[2]==Author:
                count+=1
    except EOFError:
        pass
    return count
    file.close()

#To test working of functions
def testProgram():
    while True:
        createFile()
        choice = input("Add more record (y/n)? ")
        if choice in 'Nn':
            break
    Author = input('Enter author name to search: ')
    n = countRec(Author)
    print("No of books are",n)

testProgram()

Enter book number: 2
Enter book Name: harrypotter
Enter author: albus
Enter price: 342
Add more record (y/n)? y
Enter book number: 1
Enter book Name: ikagai
Enter author: jhumpa
Enter price: 948
Add more record (y/n)? n
Enter author name to search: albus
No of books are 1

In [11]:
class Networkerror(RuntimeError):

  def _init_(self, arg):

   self.args = arg

try:

  raise Networkerror("Bad hostname")

except Networkerror.e:

  print (e.args)

AttributeError: ignored

In [8]:
# -*- coding: utf-8 -*-
"""
Created on Tue May 10 13:46:49 2022
@author: smita
"""
# This method prompts the user for the value to be used in distance calculations
# 1=Manhattan, 2=Euclidean, 3>=Minkowski
# I have limited the input to 1-9 for simplicity
def get_dist_scale(enteredVal):
    while True:
        try:
            enteredInt = int(enteredVal)
            assert (enteredInt <= int(9)), "Value greater than 9"
            assert (enteredInt >= int(1)), "Value less than 1"
            return enteredInt          
        except ValueError:
            print("Invalid Input, try againn")
            enteredVal = input("Enter distance parameter: n1: for Manhattann2: for Euclideann>=3: for Minkowskin")
            get_dist_scale(enteredVal)
        except AssertionError:
            print("Value outside 1-9.n")
            enteredVal = input("Enter distance parameter: n1: for Manhattann2: for Euclideann>=3: for Minkowskin")
            get_dist_scale(enteredVal)
            return get_dist_scale(enteredVal)

enteredVal = input("Enter distance parameter: n1: for Manhattann2: for Euclideann>=3: for Minkowskin")
distanceType = get_dist_scale(enteredVal)

Enter distance parameter: n1: for Manhattann2: for Euclideann>=3: for Minkowskin2